services:

  mysql_db1:
    image: mysql:latest
    container_name: mysql_db1
    environment:
      MYSQL_ROOT_PASSWORD: orders-password
      MYSQL_DATABASE: orders_db
    volumes:
      - orders_db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-microservice:
    build:
      context: ../carrito/microservicios_orders-master
      dockerfile: Dockerfile
    container_name: orders-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db1:3306/orders_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=orders-password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8781/eureka/
    depends_on:
      mysql_db1:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8081:8080"

  mysql_db2:
    image: mysql:latest
    container_name: mysql_db2
    environment:
      MYSQL_ROOT_PASSWORD: users-password
      MYSQL_DATABASE: users_db
    volumes:
      - users_db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  users-microservice:
    build:
      context: ../carrito/microservicios_user-main
      dockerfile: Dockerfile
    container_name: users-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db2:3306/users_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=users-password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8781/eureka/
    depends_on:
      mysql_db2:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8082:8080"

  mysql_db3:
    image: mysql:latest
    container_name: mysql_db3
    environment:
      MYSQL_ROOT_PASSWORD: products-password
      MYSQL_DATABASE: products_db
    volumes:
      - products_db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  products-microservice:
    build:
      context: microservicios_flight
      dockerfile: Dockerfile
    container_name: products-microservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db3:3306/products_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=products-password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8781/eureka/
    depends_on:
      mysql_db3:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

    networks:
      - app-network
    ports:
      - "8083:8080"

  eureka-server:
    build:
      context: ../carrito/discoverservices
      dockerfile: Dockerfile
    container_name: eureka-server
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
    networks:
      - app-network
    ports:
      - "8781:8781"

networks:
  app-network:
    driver: bridge

volumes:
  orders_db_data:
  users_db_data:
  products_db_data:
