#spring.application.name=api_gateway

server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking_route
          uri: lb://Booking
          predicates:
            - Path=/api/booking/**
        - id: flight_route
          uri: lb://microservicios_flight
          predicates:
            - Path=/api/flight/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka
